<?php
/**
 * Created by PhpStorm.
 * User: Suraj
 * Date: 2/16/2019
 * Time: 11:40 PM
 */


require_once "../config.php";
require_once "../header.php";
echo "<div id=\"main-slide3\" class=\"carousel slide\" data-ride=\"carousel\">
   
    <div class=\"carousel-inner\">
        <div class=\"carousel-item active\">
            <img class=\"d-block w-100\" src=\"/assets/images/slider/bg.png\" alt=\"First slide\">
            <div class=\"carousel-caption d-md-block\">
                <h1 class=\"animated wow fadeInDown hero-heading\" data-wow-delay=\".4s\">Terms Of Service<br><br><br></h1>
                <!--Btns here-->
                </div>
        </div>
        




  
        <section class=\"material-tabs-section section-padding\">
<div class=\"container\">
<div class=\"row\">

<div class=\"col-md-12 material-title-section wow animated fadeInLeft\" data-wow-delay=\".2s\">
<h1 class=\"section-title\">TERMS OF SERVICE</h1>
</div>
</div>
<div class=\"row mt-2 wow animated fadeInUp\" data-wow-delay=\".4s\">
<div class=\"col-md-12\">
<div class=\"Material-tab-default\">

<!--Registration process section -->


<div class=\"col-md-8\">
<p>Please read the terms and conditions set out below carefully before ordering any product or service from our website or mobile application or any other mode. By using or ordering any product or service from our website or mobile application or any other mode including by any computer equipment or by phone/mobile or by any electronic device you agree to be bound by these Terms and Conditions.</p></div>
<div class=\"col-md-8\">
<a href=\"#\"><i class=\"material-icons mdi mdi-bookmark-outline\"></i>GENERAL

</a>
<p>In terms of the Information Technology Act, 2000, this document is an electronic record. Being generated by a computer system it does not require any physical or digital signatures.

</p>
</div>
<div class=\"col-md-8\">
<a href=\"#\"><i class=\"material-icons mdi mdi-bookmark-outline\"></i>USER OBLIGATIONS</a>
<p>By visiting our website and accessing the information, resources, services, products, and tools we provide, you understand and agree to accept and adhere to the terms and conditions as stated in this policy, along with the terms and conditions as stated in our Privacy Policy.<br>

-By signup or sign in a mobile application, you are agreeing to additional terms of use with regard to our product i.e. business chat platform. You are advised to read additional terms of use carefully before sign in to application on your mobile devices.<br>

 -You further agree there is no intention to solicit any engagements from you which are statutorily mandated to be performed by relevant professionals like practicing CA's, CS's, Lawyers etc. and neither will TROZORRO.com be implied to be propagating any non-compliance via write-ups, blog posts, articles, notification, comments etc<br>

-You agreed upon that we will use our company email id or mobile number or both in various government application in order to receive OTP so that we can serve you and deliver the requisite service promptly. The rationale behind that our team requires unique token/OTP which carry self-life of shorter time in order to access the application and most of the time you are not available to provide OTP/tokens to us on an immediate basis. Your kind cooperation in this regard is highly appreciated.<br>

 -We reserve the right to change these terms & conditions from time to time without notice. You acknowledge and agree that it is your responsibility to review these terms & conditions periodically to familiarize yourself with any modifications. Your continued use of this site after such modifications will constitute acknowledgment and agreement of the modified terms and conditions.<br>

 -In order to avail our professional & other services, you may be required to provide certain information about yourself (such as identification proof, address proof, email, phone number, contact details, etc.). You agree that any information you provide will always be accurate, correct, and up to date.<br>

 -Accessing (or attempting to access) any of our Resources by any means other than through the means we provide, is strictly prohibited. You specifically agree not to access (or attempt to access) any of our Resources through any automated, unethical or unconventional means.<br>

 -Engaging in any activity that disrupts or interferes with our Resources, including the servers and/or networks to which our Resources are located or connected, is strictly prohibited.<br>

-By using this site, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this site.<br>

 -TROZORRO grants you permission to view this site and to print individual pages from this site for your own personal, non-commercial use. You may not modify, copy (except as set forth in the preceding sentence), distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer or sell any information, material, software, products or services from this site, without prior written approval from the TROZORRO. You represent and warrant to the Company that you will not use this site for any purpose that is unlawful, immoral or prohibited by these terms, conditions, and notices. If you do not agree and accept without modification the notices, terms, and conditions set forth herein, do not use this site. Other than this agreement and any other written agreements between you and the TROZORRO, the TROZORRO will not enter into any agreement with you or obligation to you through this site and no attempt to create such an agreement or obligation will be effective.<br>

-The content provided is for information purposes alone and does not substitute for specific advice whether investment, legal, taxation or otherwise. TROZORRO disclaims all liability for damages caused by the use of content on the site.<br>

-All the offers and discounts communicated to you over email or telephone shall be valid till date as specified with offers. In case offers/discounts validity period not specified then offers & discounts communicated to you shall be valid for a maximum of 7 days from the date on which offer or discount communicated to you. We are not liable to extend the benefits of offers beyond its validity period.<br>

-All responsibility and liability for any damages caused by downloading of any data are disclaimed.

-You agree that in case of any deficiency founds in our committed services TROZORRO shall be liable only to the extent of the amount paid by you to TROZORRO. No any other claims shall be entertained.<br>

-You agree that we, including our employees, are free to change your dashboard password without prior permission to ensure a better experience and quality service.<br>

-You are solely responsible any consequences, losses, or damages that we may directly or indirectly incur or suffer due to any unauthorized activities conducted by you, as explained above, and may incur criminal or civil liability.<br>

-You agree neither TROZORRO nor any of its employees or consultant shall be liable for any loss, expense or damage incurred due to \"any act of\" or \"any act occurs to\" any affiliate vendors, agents or any other 3rd party who are associated with TROZORRO whether directly or indirectly.<br>

-You agree that you will not upload, post, share, or otherwise distribute any content on our web public space which is illegal, threatening, defamatory, abusive, harassing, defame, degrading, intimidating, fraudulent, deceptive, invasive, racist, or contains any type of suggestive, inappropriate, or explicit language, contains any type of unauthorized or unsolicited advertising;<br>

-We have the right at our sole discretion to remove any content that, we feel in our judgment does not comply with this terms & conditions, along with any content that we feel is otherwise offensive, harmful, objectionable, inaccurate, or violates any 3rd party copyrights or trademarks. We are not responsible for any delay or failure in removing such content. If you post content that we choose to remove, you hereby consent to such removal and consent to waive any claim against us.<br>

 
</p>
</div>
<div class=\"col-md-8\">
<a href=\"#\"><i class=\"material-icons mdi mdi-bookmark-outline\"></i>TERMINATION OF USE</a>
<p>You agree that we may, at our sole discretion, reserve the rights to suspend or terminate your access to all or part of our website and resources with or without notice and for any reason, including, without limitation, breach of this terms & conditions and to take all necessary measures to prevent access to any services or termination of services if the terms are not complied with or are contravene or violation suspected.</p></div>
<div class=\"col-md-8\">
<a href=\"#\"><i class=\"material-icons mdi mdi-bookmark-outline\"></i>THIRD PARTY INFORMATION</a>
<p>All text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music and artwork (collectively, \"Content\"), apart from the ones owned by Us, is a third party user generated content and We have no control over such third party user generated content.

Other than when provided for, the use of such content and it being reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including \"mirroring\") to any other computer, server, Website or another medium for publication or distribution or for any commercial enterprise, without Our express prior written consent is not allowed.

The content that you post will become Our property and You grant Us the worldwide, perpetual and transferable rights in such Content. We shall be entitled to, consistent with Our Privacy Policy as adopted in accordance with applicable law, use the Content or any of its elements for any type of use forever, including but not limited 

to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include the Content You provide and are not entitled to any payment or other compensation for such use.</p></div>
 </div>
<div class=\"col-md-8\">
<a href=\"#\"><i class=\"material-icons mdi mdi-bookmark-outline\"></i>DISPUTE RESOLUTION</a>
<p>This Agreement, the construction, enforcement and the interpretation of its terms and any disputes arising out of it shall be governed by the Laws of India and shall be subject to the courts located in Delhi, and You hereby submit to the personal jurisdiction of such courts.</p></div>
</div>
</div>
</div>
</div>
</div>
</section>

";





require_once "../page_elements/contact_form_design.php";

require_once "../footer.php";